"""Test dir structure

Revision ID: 0a1f6390d93a
Revises: c5691824c580
Create Date: 2020-09-18 11:11:01.263868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a1f6390d93a'
down_revision = 'c5691824c580'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('measurements', sa.Column('timestamsp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('measurements', 'timestamsp')
    # ### end Alembic commands ###
