"""Remove test column

Revision ID: 2ed6e1dcdbd8
Revises: 0a1f6390d93a
Create Date: 2020-09-18 11:11:42.272737

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2ed6e1dcdbd8'
down_revision = '0a1f6390d93a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('measurements', 'timestamsp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('measurements', sa.Column('timestamsp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
