"""Third migration 

Revision ID: 6aac30ea58e5
Revises: 8dfdcf221d1a
Create Date: 2020-09-19 18:00:08.590290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6aac30ea58e5'
down_revision = '8dfdcf221d1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensors', sa.Column('date_add2ed', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sensors', 'date_add2ed')
    # ### end Alembic commands ###
