"""Remove test column from database

Revision ID: ccaf1b404a99
Revises: ed657807998c
Create Date: 2020-09-20 11:40:44.515412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccaf1b404a99'
down_revision = 'ed657807998c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensors', sa.Column('date_added2', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sensors', 'date_added2')
    # ### end Alembic commands ###
