FROM node:12 as build-stage

# Create app directory
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH

# Install app dependencies
COPY package*.json /app/

RUN npm install --silent

# Bundle app source
COPY . /app

# EXPOSE 8080
CMD [ "npm", "run", "build" ]

# production stage
FROM nginx:stable-alpine as production-stage
RUN ls -la /app/dist
COPY --from=build-stage /app/dist /usr/share/nginx/html
EXPOSE 8080
CMD ["nginx", "-g", "daemon off;"]


# build environment
FROM node:12.2.0-alpine as build
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY package.json /app/package.json
RUN npm install --silent
RUN npm install @vue/cli@3.7.0 -g
COPY . /app
RUN npm run build

# production environment
FROM nginx:1.16.0-alpine
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
