"""Test new dir structure

Revision ID: 28abbd4b36ab
Revises: c82cec62ef80
Create Date: 2020-09-16 14:47:51.930230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28abbd4b36ab'
down_revision = 'c82cec62ef80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('measurements', sa.Column('test', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('measurements', 'test')
    # ### end Alembic commands ###
