"""Change data to datapoint

Revision ID: c5691824c580
Revises: d98801f542e8
Create Date: 2020-09-17 10:50:05.208305

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c5691824c580'
down_revision = 'd98801f542e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('measurements', sa.Column('datapoint', sa.Float(), nullable=True))
    op.drop_column('measurements', 'data')
    op.drop_column('sensors', 'test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensors', sa.Column('test', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('measurements', sa.Column('data', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('measurements', 'datapoint')
    # ### end Alembic commands ###
