version: '3'

services:
  db:
    build:
      context: ./services/postgres
      dockerfile: Dockerfile
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - ./backend/.env.prod.db
  web:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    command: gunicorn app.main:app --bind 0.0.0.0:5000 -w 4 -k uvicorn.workers.UvicornWorker
    expose:
      - 5000
    labels:
      - traefik.enable=true
      - traefik.http.routers.backend.rule=PathPrefix(`/api`)|| PathPrefix(`/docs`) || PathPrefix(`/redoc`) || PathPrefix(`/openapi.json`)
    depends_on:
      - db

  traefik:
    image: traefik:v2.2
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./services/traefik/traefik.prod.toml:/etc/traefik/traefik.toml

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile-prod
    labels:
      - traefik.enable=true
      - traefik.http.routers.frontend.rule=PathPrefix(`/`)
    expose:
      - 8080

volumes:
  pg_data: {}
