version: '3'

services:
  db:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    expose:
      - 5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=sensor_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '5057:5057'
    depends_on:
      - db

volumes:
  pg_data: {}

