"""Add cascade condition

Revision ID: c82cec62ef80
Revises: f493edb4b2a8
Create Date: 2020-09-16 11:54:29.524129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c82cec62ef80'
down_revision = 'f493edb4b2a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('measurements_sensor_id_fkey', 'measurements', type_='foreignkey')
    op.create_foreign_key(None, 'measurements', 'sensors', ['sensor_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'measurements', type_='foreignkey')
    op.create_foreign_key('measurements_sensor_id_fkey', 'measurements', 'sensors', ['sensor_id'], ['id'])
    # ### end Alembic commands ###
