"""Test new dir structure

Revision ID: cef81da7084a
Revises: 28abbd4b36ab
Create Date: 2020-09-16 14:48:26.122132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cef81da7084a'
down_revision = '28abbd4b36ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
