"""Add cascade condition

Revision ID: d98801f542e8
Revises: cef81da7084a
Create Date: 2020-09-16 16:02:56.571505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd98801f542e8'
down_revision = 'cef81da7084a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
